### PR TITLE
Test updates by playing a game

### PR DESCRIPTION
**Pull request by AttackingOrDefending**
This PR downloads Fairy-SF and plays one game to test the update. It will only work if someone puts their token https://github.com/AttackingOrDefending/Lishogi-Bot/blob/test-bot/tests.py#L84. I was thinking that you could make a new bot (because you are a developer and moderator) and put its token here so every PR will be tested by playing a game.

### CODE REVIEW

**Comment by TheYoBots** [comment]
I have converted this to a draft I’ll push some changes soon, and then provide a review if any issue is faced. Thanks!

**Comment by TheYoBots** [comment]
@AttackingOrDefending Just in case you haven’t seen this yet https://github.com/AttackingOrDefending/Lishogi-Bot/pull/1

**Comment by AttackingOrDefending** [comment]
I lowerd move overhead and AI level because the bot was losing some games because it was playing very fast. It failed the test because it was playing 2 games in a row. If you rerun the test, it shouldn't fail.

**Comment by TheYoBots** [comment]
Thanks!

**Pull request merged**
