### PR TITLE
Add support for homemade engines

### PR DESCRIPTION
**Pull request by AttackingOrDefending**
A lot of functions were moved from USIEngine to EngineWrapper, so the Homemade engines would inherit these classes. Also, added the changes for correspondence already in lichess-bot.

### CODE REVIEW

**Comment by TheYoBots** [comment]
Nice, you’ve even included the changes here (https://github.com/ShailChoksi/lichess-bot/commit/444c4b61e307d64957d26398cd436839273c0182) right?

**Comment by AttackingOrDefending** [comment]
Now they are added.

**Comment by TheYoBots** [comment]
Ok, I think you have fixed a few other things too, could you please explain that as well? Also the `EngineWrapper.search()` method was removed as it was not used, are you using it now?

**Comment by AttackingOrDefending** [comment]
I can change self.search to self.go. Do you want me to change it? It will cause a few changes:

1. Homemade engines would have to implement go instead of search
2. Print stats will have to be in both search_with_ponder and search_for

**Comment by TheYoBots** [comment]
Ok, thanks for explaining, you do not require to change it. Just could you explain what changes you have made that aren’t related to the homemade engine. Example, the bot giving the engine name to the `!name` command.

**Comment by AttackingOrDefending** [comment]
The !name command is printing the engine name along with the version and bot name like it is in lichess-bot. Now it will print "AttackingOrDefending running YaneuraOu (Lishogi-Bot v1.1.0)". The if len(cmds) > 0 in search_with_ponder, is moved to engine_ctrl with "and nodes is None and depth is None and movetime is None". search_for now calls search instead of go. first_search is removed and we are using search_for. print_stats() and get_stats() are changed to be like in lichess-bot (with a few changes). name() is changed to be like in lichess-bot. ponderhit, stop, quit, kill_process are added in EngineWrapper so Homemade engines can inherit them. go_commands is changed to be like in lichess-bot (they weren't working before because it tried to find them inside the 'engines' but it was inside 'engines.usi_options'). is_usi_ponder is renamed to can_ponder and we remove "is_usi and " because homemade engines can ponder. Added the changed for corresponce from lichess-bot to lishogi-bot. Changed play_first_move to choose_first_move which returns the move (the engine will also be able to ponder after the first move). Moved "if is_usi_ponder and ponder_move is not None:" to inside start_pondering like it was after the refactor in lichess-bot (https://github.com/ShailChoksi/lichess-bot/pull/270). Moved engine.print_stats() to search.

**Comment by TheYoBots** [comment]
Thanks!

**Pull request merged**
