### PR TITLE
Ponder

### PR DESCRIPTION
**Pull request by AttackingOrDefending**
Same as https://github.com/TheYoBots/Lishogi-Bot/pull/20.

### CODE REVIEW

**Comment by AttackingOrDefending** [comment]
It is not the fault of the PR that the test failed. It made too many requests to connect to lishogi.

**Comment by TheYoBots** [comment]
Thanks for your PR.

Just a few pointers:
- You do not need to upstream to the latest master build if commits have been pushed after you created a PR and sometimes it isn’t even required.
- `ponder` was implemented in lichess-bot (first for only the UCI protocol and later for the XBoard protocol) in these 2 PRs (https://github.com/ShailChoksi/lichess-bot/pull/185 & https://github.com/ShailChoksi/lichess-bot/pull/288 and other PRs that fixed bugs in these), but this has been possible and also made a difference as `ponder` is directly supported by python-chess (You can find few interesting discussions here https://github.com/ShailChoksi/lichess-bot/pull/104 , this is the PR that lead to it being implemented for the UCI protocol by noobpwnftw), but not supported by python-shogi.

**Comment by TheYoBots** [comment]
Hi @AttackingOrDefending there can even be a separate ponder for specifically correspondence like it has been implemented in [lichess-bot](https://github.com/ShailChoksi/lichess-bot/blob/master/config.yml.default#L55). If you know how and are sure about the steps to do so could you either make a new PR or you could implement it here itself for more uniformity.

**Comment by TheYoBots** [comment]
@AttackingOrDefending If you would not like to or are not sure of how to implement ponder for correspondence, then please do mention it. I’ll merge this PR if that is the case.

**Comment by AttackingOrDefending** [comment]
I will look into it next week. I don't think it would be hard to implement it (probably it will be just copying the code with little to no changes).

**Comment by AttackingOrDefending** [comment]
Do you want every update from https://github.com/ShailChoksi/lichess-bot/pull/316 (will make a new PR) or just a seperate ponder in config.yml only for correspondence games (will implement it in this PR)?

**Comment by TheYoBots** [comment]
Do anything that you find easier. Eventually I would completely update everything from https://github.com/ShailChoksi/lichess-bot/pull/316 even if you don’t.

**Comment by AttackingOrDefending** [comment]
@TheYoBots I also added a small update to make the tests work better. I lowered move overhead because the bot was moving immediately (2 seconds Byoyomi - 2 seconds move overhead = 0 seconds, although it probably has Minimum Thinking Time (0.02 seconds if it is the same as standard SF)).

**Comment by TheYoBots** [comment]
Thanks for your changes! Is this ready to be merged or there are a few more code changes you will be doing here?

**Comment by AttackingOrDefending** [comment]
It is ready.

**Pull request merged**
