### PR TITLE
Major Refactor

### PR DESCRIPTION
**Pull request by MarkZH**
This pull request mostly replicates the changes in these pull requests from lichess-bot:

ShailChoksi/lichess-bot#270
ShailChoksi/lichess-bot#259

Code duplication is much reduced and other code is simplified. It also fixes some bugs.

Please test and comment.

Major changes:

- Unify startup move handling and subsequent move handling into "gameState" branch of main loop
- Create functions for starting pondering and getting results
- Create new board on every "gameState" update
- Simplify is_engine_move()
- Engine constructors do not need a board instance
- Delete unused EngineWrapper.search() method

Bugs fixed:

- If an engine does not output anything when choosing a move ([gpsfish-minimal](https://gps.tanaka.ecc.u-tokyo.ac.jp/gpsshogi/pukiwiki.php?GPSFish), for example), the self.info field in Engine is never set, leading to an unrecoverable error when engine.print_stats() is called.
- report_game_result() called on non-existent _protocol field.

Minor changes:

- Use idiomatic comparisons for None ("is None" or "is not None")
- Fix spacing with parentheses
- Delete trailing whitespace

### CODE REVIEW

**Comment by TheYoBots** [comment]
Oh wow thanks! I’ll just run a few tests and then merge this soon. Thanks again.

**Comment by AttackingOrDefending** [comment]
I think start_pondering should be after make_move, so the bot can send the move faster.

**Comment by MarkZH** [comment]
Pondering now starts after make_move. Plus, a few extra functions extracted out of the main game loop.

**Comment by TheYoBots** [comment]
Just tested this. There are some errors that I face when I enable ponder (not the usi option). When ponder is set to false it works well, but faces an error when enabled.

These are the error logs:

```
          .   _/\_
          .  //o o\\
          .  ||    ||  lishogi-bot 1.1.0
          .  ||    ||
          .  ||____||  Play on Lishogi with a bot

2021-06-28 12:24:17,016: [94m  Welcome YoBot_v2![0m
2021-06-28 12:24:17,016: [94m  You're now connected to https://lishogi.org/ and awaiting challenges.[0m

2021-06-28 12:24:34,432: [94m  Accept Bullet casual challenge from YohaanSethNathan(1371)[0m
2021-06-28 12:24:34,462: [94m  --- Process Queue. Total Queued: 1. Total Used: 0[0m
2021-06-28 12:24:34,463: [94m  --- Process Used. Total Queued: 0. Total Used: 1[0m
2021-06-28 12:24:34,716: [94m  +++ https://lishogi.org/zWGV53O1/sente Bullet vs YohaanSethNathan(1371?)[0m

2021-06-28 12:24:34,717: [94m  move: 1[0m
2021-06-28 12:24:34,718: [94m  position sfen lnsgkgsnl/1r5b1/ppppppppp/9/9/9/PPPPPPPPP/1B5R1/LNSGKGSNL b - 1 moves [0m
2021-06-28 12:24:34,718: [94m  go movetime 1000[0m
2021-06-28 12:24:35,719: [94m  score: {'cp': 122}[0m
2021-06-28 12:24:35,719: [94m  depth: 14[0m
2021-06-28 12:24:35,720: [94m  nodes: 175783[0m
2021-06-28 12:24:35,720: [94m  nps: 175432[0m

2021-06-28 12:24:37,218: [94m  move: 3[0m
2021-06-28 12:24:37,218: [94m  Searching for btime 58100 wtime 60000[0m
2021-06-28 12:24:37,218: [94m  position startpos moves 7g7f 3c3d[0m
2021-06-28 12:24:37,218: [94m  go btime 58100 wtime 60000 byoyomi 0 binc 0 winc 0[0m
2021-06-28 12:24:37,408: [94m  score: {'cp': 144}[0m
2021-06-28 12:24:37,409: [94m  depth: 12[0m
2021-06-28 12:24:37,409: [94m  nodes: 30630[0m
2021-06-28 12:24:37,409: [94m  nps: 160366[0m
2021-06-28 12:24:37,432: [94m  Backing off play_game(...) for 0.0s (AttributeError: 'int' object has no attribute 'game')[0m
2021-06-28 12:24:39,024: [94m  +++ https://lishogi.org/zWGV53O1/sente Bullet vs YohaanSethNathan(1371?)[0m

2021-06-28 12:24:39,119: [94m  move: 5[0m
2021-06-28 12:24:39,120: [94m  Searching for btime 57990 wtime 59730[0m
2021-06-28 12:24:39,125: [94m  position startpos moves 7g7f 3c3d 4i5h 4c4d[0m
2021-06-28 12:24:39,126: [94m  go btime 57990 wtime 59730 byoyomi 0 binc 0 winc 0[0m
2021-06-28 12:24:41,822: [94m  score: {'cp': 119}[0m
2021-06-28 12:24:41,823: [94m  depth: 15[0m
2021-06-28 12:24:41,823: [94m  nodes: 272135[0m
2021-06-28 12:24:41,823: [94m  nps: 100940[0m
2021-06-28 12:24:42,021: [94m  Backing off play_game(...) for 1.9s (AttributeError: 'int' object has no attribute 'game')[0m
2021-06-28 12:24:46,249: [94m  +++ https://lishogi.org/zWGV53O1/sente Bullet vs YohaanSethNathan(1371?)[0m

2021-06-28 12:24:46,257: [94m  move: 7[0m
2021-06-28 12:24:46,257: [94m  Searching for btime 52080 wtime 59730[0m
2021-06-28 12:24:46,257: [94m  position startpos moves 7g7f 3c3d 4i5h 4c4d 2g2f 8b4b[0m
2021-06-28 12:24:46,257: [94m  go btime 52080 wtime 59730 byoyomi 0 binc 0 winc 0[0m
2021-06-28 12:24:47,415: [94m  score: {'cp': 198}[0m
2021-06-28 12:24:47,416: [94m  depth: 12[0m
2021-06-28 12:24:47,416: [94m  nodes: 100252[0m
2021-06-28 12:24:47,416: [94m  nps: 86498[0m
2021-06-28 12:24:47,450: [94m  Backing off play_game(...) for 3.4s (AttributeError: 'int' object has no attribute 'game')[0m
```

And this continues to happen until the game is lost on time.

**Comment by MarkZH** [comment]
Your error was caused by a typo in my code. [Fixing that](https://github.com/TheYoBots/Lishogi-Bot/pull/29/commits/332a5cf39623788619bfbde97bb59d5bfbbdb666) revealed another error, [which was fixed](https://github.com/TheYoBots/Lishogi-Bot/pull/29/commits/ee04698492c983553f71d330ebd58922bd491a52).

I'm a little suspicious of the clock calculations. Could you confirm that the `go btime ... wtime ... etc` commands send the right clock times for normal moves and pondering?

**Comment by TheYoBots** [comment]
Thanks, I just tested these changes and everything seems to be fine. Regarding the clock calculations, I tested it in [this game](https://lishogi.org/SLLrdBB4) and on [move 40](https://lishogi.org/SLLrdBB4/gote#40) this is what I see `go btime 24390 wtime 36170 byoyomi 0 binc 0 winc 0` which seems accurate.

**Comment by MarkZH** [comment]
This last commit should fix the most recent error. It does make me wonder why the same issue doesn't seem to be present in lichess-bot.

**Comment by MarkZH** [comment]
On a side note, I think there's been an update to lichess (lila) that the main lishogi.org code might want to incorporate. The change stops two messages from being sent at the end of a game that ends in checkmate. Right now, when a lishogi game ends in checkmate, the following two messages are sent (preceded by the last move from my bot):

    2021-06-28 23:56:00,028: https://lishogi.org:443 "POST /api/bot/game/xhpITQy1/move/G*g2 HTTP/1.1" 200 11

    2021-06-28 23:56:00,057: Update: {'type': 'gameState', 'moves': 'i3i4 d9e8 h3h4 g7g6 h4h5 h8g7 g1g2 g9f8 h5h6 h7h6 g3g4 c9d8 i4i5 b7b6 g4g5 g6g5 a3a4 b6b5 e1e2 g5g4 c1c2 b8b6 i5i6 g7e5 f3f4 e5f4 h2i2 h9g7 i6i7+ g7f5 f1f2 b6e6 b2c1 b5b4 g2f3 f4g3+ b3b4 i9i7 i2i7+ P*b2 P*g2 g3f2 e2f2 b2b1+ c2b1 N*b3 c1d2 b3a1+ B*h7 e6e3+ d2e3 f5e3+ f2e3 a1b1 i7i9 f8g9 P*f8 B*g1 L*f2 e8f8 d1e2 e9d9 f3f4 b1c1 h7e4+ c1c2 b4b5 c2c3 g2g3 g4g3+ f4g3 L*h2 h1i3 c7c6 i9i5 g9h8 R*b8 d8c9 b8b9+ G*d5 i5d5 S*c8 b9a9 P*i2 P*h7 P*g4 g3g4 P*b9 P*c7 g1f2 e2f2 c3d3 d5d3 L*d6 h7h8+ d6d3+ e4d3 i2i1+ B*e5 R*e1 N*e2 L*e6 c7c8+ c9c8 d3f5 e6e5 f5e5 e1d1 e3f3 d1d3+ P*e3 B*d6 N*e6 e7e6 S*e7 d6e7 e5e6 e7h4 P*c7 S*e4 f3g2 h4f2+ g2f2 d3e3 f2g2 N*h4 g2g1 G*g2', 'btime': 4340, 'wtime': 50, 'binc': 0, 'winc': 0, 'byo': 0, 'sdraw': False, 'gdraw': False, 'status': 'mate'}

    2021-06-28 23:56:00,089: Update: {'type': 'gameState', 'moves': 'i3i4 d9e8 h3h4 g7g6 h4h5 h8g7 g1g2 g9f8 h5h6 h7h6 g3g4 c9d8 i4i5 b7b6 g4g5 g6g5 a3a4 b6b5 e1e2 g5g4 c1c2 b8b6 i5i6 g7e5 f3f4 e5f4 h2i2 h9g7 i6i7+ g7f5 f1f2 b6e6 b2c1 b5b4 g2f3 f4g3+ b3b4 i9i7 i2i7+ P*b2 P*g2 g3f2 e2f2 b2b1+ c2b1 N*b3 c1d2 b3a1+ B*h7 e6e3+ d2e3 f5e3+ f2e3 a1b1 i7i9 f8g9 P*f8 B*g1 L*f2 e8f8 d1e2 e9d9 f3f4 b1c1 h7e4+ c1c2 b4b5 c2c3 g2g3 g4g3+ f4g3 L*h2 h1i3 c7c6 i9i5 g9h8 R*b8 d8c9 b8b9+ G*d5 i5d5 S*c8 b9a9 P*i2 P*h7 P*g4 g3g4 P*b9 P*c7 g1f2 e2f2 c3d3 d5d3 L*d6 h7h8+ d6d3+ e4d3 i2i1+ B*e5 R*e1 N*e2 L*e6 c7c8+ c9c8 d3f5 e6e5 f5e5 e1d1 e3f3 d1d3+ P*e3 B*d6 N*e6 e7e6 S*e7 d6e7 e5e6 e7h4 P*c7 S*e4 f3g2 h4f2+ g2f2 d3e3 f2g2 N*h4 g2g1 G*g2', 'btime': 4340, 'wtime': 50, 'binc': 0, 'winc': 0, 'byo': 0, 'sdraw': False, 'gdraw': False, 'status': 'mate', 'winner': 'gote'}

The only difference between the last two messages from lishogi is that the second one has the field ` 'winner': 'gote'`. So, the first message after a game ends contains incomplete information as it does not tell who won.

**Comment by TheYoBots** [comment]
I still face a similar error during the game completion state.

```
Exception in thread Thread-37:
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/app/.heroku/python/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/app/lishogi-bot.py", line 346, in ponder_thread_func
    best_move, ponder_move = engine.search_with_ponder(game, board, btime, wtime, binc, winc, byo, True)
  File "/app/engine_wrapper.py", line 91, in search_with_ponder
    best_move, ponder_move = self.engine.go(
  File "/app/engine_ctrl.py", line 155, in go
    command, arg = self.recv_usi()
  File "/app/engine_ctrl.py", line 65, in recv_usi
    command_and_args = self.recv().split(None, 1)
  File "/app/engine_ctrl.py", line 57, in recv
    raise EOFError()
EOFError
```

**Comment by AttackingOrDefending** [comment]
I think you should add
```python
def quit(self):
        self.send("quit")
```
in engine_ctrl.py, 
change quit in engine_wrapper (line 51) to quit and not kill_process,
change stop in engine_wrapper (line 103) to stop and not kill_process,
change `engine.engine.stop()` to `engine.stop()` in lichess-bot (line 364) and
change lines 306-308 in lishogi-bot to
```python
engine.stop()
engine.quit()
if ponder_thread is not None:
        ponder_thread.join()
engine.engine.kill_process()
```

**Comment by MarkZH** [comment]
That should do it.

@AttackingOrDefending Thanks for the suggestions.

**Comment by TheYoBots** [comment]
Thank you so much for doing this!

**Pull request merged**
