### PR TITLE
Print stats

### PR DESCRIPTION
**Pull request by AttackingOrDefending**
Prints stats and makes !eval work.

### CODE REVIEW

**Comment by TheYoBots** [comment]
Hi! Thanks for your PR. Are you completely sure this works though? I believe this would work in lichess-bot as it uses python chess which supports providing such info, but not sure whether this is supported by python-shogi.

**Comment by AttackingOrDefending** [comment]
You can test this. The code I added didn't use python-shogi. The code already collected info, I just print it.

**Comment by TheYoBots** [comment]
Thanks, I’ll merge this in. Just a question, this will only work with engines that use values like 'score', 'depth', 'nodes' or 'nps' right? Or would be applicable for any engine running under the usi protocol?

**Comment by AttackingOrDefending** [comment]
I think most of the engines use this, since the naming was already in engine_ctrl.py and most shogi engines are based on Stockfish.

**Pull request merged**
