### PR TITLE
Update config.yml.default

### PR DESCRIPTION
**Pull request by barca-cloud**
better greeting and just write your token not xxxxxxxxxxxxxxxxxxxxxxxxxxxx

### CODE REVIEW

**Comment by TheYoBots** [comment]
Umm…. Anything useful this does?

**Comment by TheYoBots** [comment]
That’s not the point

**Comment by barca-cloud** [comment]
Anyway but @TheYoBots  i have one favour only one can you add welcome message ro my github sorce it private.

**Comment by barca-cloud** [comment]
https://github.com/barca-cloud/thechessbot

**Comment by barca-cloud** [comment]
If that having error tommorow i will add you in the repo.

**Pull request closed without merging**
