### PR TITLE
Lishogi Bot Build

### PR DESCRIPTION
**Pull request by TheYoBots**
Sorry I made a mistake while pushing a commit and it lost most of everything. This PR brings that back.

### CODE REVIEW

**Review by SriMethan — CHANGES_REQUESTED** [review]
Should probably need to add CONFIG['engine']['usi_options']['EvalDir']

**Comment by TheYoBots** [comment]
> need to add Eval Dir in the usi_options

It is set to default as `eval`.

Now let me guess, you'll delete your comment xD

**Comment by SriMethan** [comment]
How can YaneuraOu linux executable run on windows os?

**Comment by SriMethan** [comment]
The current Workflow runs on **runs-on: windows-latest**

**Pull request closed without merging**
