### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by RoundingExplorer**
Not required because already selected

### CODE REVIEW

**Comment by TheYoBots** [comment]
Btw,
"Play games with the bot API" scope = "bot:play" scopes

Sorry, I don’t get what you mean.

**Comment by RoundingExplorer** [comment]
Huh??

**Comment by RoundingExplorer** [comment]
('bot:play' scopes) This is not required I was saying. Feel less like an idiot

**Comment by RoundingExplorer** [comment]
So

**Comment by TheYoBots** [comment]
I think I prefer to keep that in the brackets as it would be useful for developers.

**Pull request closed without merging**
